### ISSUE TITLE
Footer-icons

### ISSUE THREAD

**Issue by tim4boom** [SeeQL-Enterprises/SeeQL#180]
**Describe the bug**
For PR #178 I tried the new icons and found the following bugs:
1) When clicking on the link icon, nothing happens. 
2) Clicking on the mail icon, an empty tab opens

**To Reproduce**
Open the website and click on the respective icons

**Screenshots**
See Slack for screen  recording

**Comment by Bruncky** [comment]
Thanks!

For the link button, click it and then Ctrl + V somewhere. It’s only supposed to copy our URL to the clipboard, that’s why nothing happens haha.

For the Mail link, is JS enabled on Gmail? I saw you’re using Brave, which blocks JS by default unless you enable it.
